### ISSUE TITLE
Indexes Inconsistent

### ISSUE THREAD

**Issue by wkgardner** [William-Gardner-Biotech/N_terminus_MSA_check#4]
For data visualization in the program it made sense to display starting from 1. It does not effect the dictionaries because their numbers are consistent starting from 1 but when you concatenate a string or index a list it is one above.

**Comment by wkgardner** [comment]
## **CURRENT** BUGS

 EMPTY

--------------------------------------------------------------------------------------------------------------

**## PREVIOUS BUGS**

4GIPG_results.txt
Traceback (most recent call last):
  File "/home/will/pythonProject1/MET_program.py", line 41, in <module>
    print("Outlier Seq No", Outlier, PTs[Outlier])
IndexError: list index out of range
**RESOLVED


4GIFX_results.txt
Traceback (most recent call last):
  File "/home/will/pythonProject1/MET_program.py", line 25, in <module>
    sorted_positions = (MET_library.regx_firM(seqs))
  File "/home/will/pythonProject1/MET_library.py", line 141, in regx_firM
    key = len(N_ter.group(0))
AttributeError: 'NoneType' object has no attribute 'group'
**RESOLVED

**Comment by wkgardner** [comment]
Indexes fixed
